// Code generated by go-swagger; DO NOT EDIT.

package audio_file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new audio file API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for audio file API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetBroadcastsBroadcastIDAudioFiles(params *GetBroadcastsBroadcastIDAudioFilesParams, authInfo runtime.ClientAuthInfoWriter) (*GetBroadcastsBroadcastIDAudioFilesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetBroadcastsBroadcastIDAudioFiles Returns a list of available audio files for a given broadcast.
*/
func (a *Client) GetBroadcastsBroadcastIDAudioFiles(params *GetBroadcastsBroadcastIDAudioFilesParams, authInfo runtime.ClientAuthInfoWriter) (*GetBroadcastsBroadcastIDAudioFilesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBroadcastsBroadcastIDAudioFilesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetBroadcastsBroadcastIDAudioFiles",
		Method:             "GET",
		PathPattern:        "/broadcasts/{broadcast_id}/audio_files",
		ProducesMediaTypes: []string{"application/vnd.api+json"},
		ConsumesMediaTypes: []string{"application/vnd.api+json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetBroadcastsBroadcastIDAudioFilesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBroadcastsBroadcastIDAudioFilesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetBroadcastsBroadcastIDAudioFiles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
