// Code generated by go-swagger; DO NOT EDIT.

package audio_file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/radiorabe/annotation-agent/annotator/archive/raar/models"
)

// GetBroadcastsBroadcastIDAudioFilesReader is a Reader for the GetBroadcastsBroadcastIDAudioFiles structure.
type GetBroadcastsBroadcastIDAudioFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBroadcastsBroadcastIDAudioFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBroadcastsBroadcastIDAudioFilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBroadcastsBroadcastIDAudioFilesOK creates a GetBroadcastsBroadcastIDAudioFilesOK with default headers values
func NewGetBroadcastsBroadcastIDAudioFilesOK() *GetBroadcastsBroadcastIDAudioFilesOK {
	return &GetBroadcastsBroadcastIDAudioFilesOK{}
}

/*GetBroadcastsBroadcastIDAudioFilesOK handles this case with default header values.

successfull operation
*/
type GetBroadcastsBroadcastIDAudioFilesOK struct {
	Payload *GetBroadcastsBroadcastIDAudioFilesOKBody
}

func (o *GetBroadcastsBroadcastIDAudioFilesOK) Error() string {
	return fmt.Sprintf("[GET /broadcasts/{broadcast_id}/audio_files][%d] getBroadcastsBroadcastIdAudioFilesOK  %+v", 200, o.Payload)
}

func (o *GetBroadcastsBroadcastIDAudioFilesOK) GetPayload() *GetBroadcastsBroadcastIDAudioFilesOKBody {
	return o.Payload
}

func (o *GetBroadcastsBroadcastIDAudioFilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetBroadcastsBroadcastIDAudioFilesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetBroadcastsBroadcastIDAudioFilesOKBody get broadcasts broadcast ID audio files o k body
swagger:model GetBroadcastsBroadcastIDAudioFilesOKBody
*/
type GetBroadcastsBroadcastIDAudioFilesOKBody struct {

	// data
	Data []*models.AudioFile `json:"data"`
}

// Validate validates this get broadcasts broadcast ID audio files o k body
func (o *GetBroadcastsBroadcastIDAudioFilesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBroadcastsBroadcastIDAudioFilesOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getBroadcastsBroadcastIdAudioFilesOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBroadcastsBroadcastIDAudioFilesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBroadcastsBroadcastIDAudioFilesOKBody) UnmarshalBinary(b []byte) error {
	var res GetBroadcastsBroadcastIDAudioFilesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
